#!/usr/bin/env python3
"""
Compendium builder — stitches every reading's guide and notes into one PDF.

Walks the repo for `*_Claude_Guide.tex` and `*_Notes.tex`, orders them
alphabetically by reading, and emits `Comprehensive Content/Compendium/compendium.tex` with each
reading as a \\part and, beneath it, the Claude guide followed by the
personal notes.

The generated file is disposable — it is rewritten from scratch on every
run and should never be hand-edited. Edit the source notes instead.

Usage:
    python3 tools/build_compendium.py            # write .tex only
    python3 tools/build_compendium.py --pdf      # write .tex and compile
    python3 tools/build_compendium.py --check    # exit 1 if stale (for hooks)

No dependencies beyond the standard library; `--pdf` shells out to latexmk.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "Comprehensive Content" / "Compendium"
OUT_TEX = OUT_DIR / "compendium.tex"

# Folders that hold no readings.
SKIP_DIRS = {
    "tools", "Exam Writing", "Comprehensive Content", "Compendium",
    ".git", "__pycache__",
}

BODY_RE = re.compile(r"\\begin\{document\}(.*)\\end\{document\}", re.DOTALL)
TITLE_RE = re.compile(r"\\title\{(.*?)\n?\}\s*\n\s*\\author", re.DOTALL)
GRAPHICS_RE = re.compile(r"(\\includegraphics)(\[[^\]]*\])?\{([^}]*)\}")

# Stripped from each body: the standalone-document furniture.
STRIP_LINES = re.compile(
    r"^\s*\\(maketitle|tableofcontents|newpage|clearpage|thispagestyle\{[^}]*\})\s*$",
    re.MULTILINE,
)

# Demote headings so each source \section sits under the reading's \part.
# Order matters: deepest first, so \section doesn't get demoted twice.
DEMOTIONS = [
    (re.compile(r"\\subsection\*"), r"\\subsubsection*"),
    (re.compile(r"\\subsection(?!\*)"), r"\\subsubsection"),
    (re.compile(r"\\section\*"), r"\\subsection*"),
    (re.compile(r"\\section(?!\*)"), r"\\subsection"),
]

PREAMBLE = r"""% ---------------------------------------------------------------
%  AUTO-GENERATED by tools/build_compendium.py — DO NOT EDIT.
%  Edit the individual reading notes and re-run the builder.
% ---------------------------------------------------------------
\documentclass[11pt]{book}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath}
\usepackage{enumitem}
\usepackage{graphicx}
\usepackage{parskip}
\usepackage{titlesec}
\usepackage{xcolor}
\usepackage[hidelinks]{hyperref}

% Sources are written as articles, so their deepest heading is \subsection.
% Under \part that lands at \subsubsection — keep it numbered and in the ToC.
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{2}

\title{\textbf{2026 Comprehensive Exam}\\[0.3em]
\large Collected Guides and Notes}
\author{Ryan Gibbons}
\date{\today}

\begin{document}
\maketitle
\tableofcontents
"""


def find_readings():
    """Return [(display_name, dir_path)] for every folder holding a reading."""
    found = {}
    for tex in REPO.rglob("*_Notes.tex"):
        d = tex.parent
        if any(part in SKIP_DIRS for part in d.relative_to(REPO).parts):
            continue
        found[d] = d.name
    for tex in REPO.rglob("*_Claude_Guide.tex"):
        d = tex.parent
        if any(part in SKIP_DIRS for part in d.relative_to(REPO).parts):
            continue
        found[d] = d.name
    # Alphabetical by the reading's own name, not its path, so the
    # Extra Readings interleave with the main list rather than clumping.
    return sorted(found.items(), key=lambda kv: kv[1].lower())


def extract_subtitle(src):
    """Pull the citation line out of \\title{...}, minus the bolded heading."""
    m = TITLE_RE.search(src)
    if not m:
        return ""
    title = m.group(1)
    # Drop the leading \textbf{...} (the "Dahl 1972 Claude Guide" part) and
    # the \large switch, keeping the human-readable citation beneath it.
    title = re.sub(r"\\textbf\{[^}]*\}\s*\\\\", "", title, count=1)
    title = title.replace(r"\large", "")
    parts = [p.strip() for p in title.split(r"\\") if p.strip()]
    return " ".join(parts)


def transform(src, reading_dir):
    """Strip a standalone .tex down to an includable body."""
    m = BODY_RE.search(src)
    body = m.group(1) if m else src
    body = STRIP_LINES.sub("", body)
    for pattern, repl in DEMOTIONS:
        body = pattern.sub(repl, body)

    # Images are referenced bare (e.g. {fig1.jpg}) and collide across
    # folders, so rewrite each to a repo-relative path.
    rel = reading_dir.relative_to(REPO).as_posix()

    def fix(match):
        cmd, opts, target = match.groups()
        if "/" in target:  # already qualified
            return match.group(0)
        return f'{cmd}{opts or ""}{{"{rel}/{target}"}}'

    body = GRAPHICS_RE.sub(fix, body)
    return body.strip()


def section_for(path, reading_dir, heading):
    src = path.read_text(encoding="utf-8")
    body = transform(src, reading_dir)
    if not body:
        return ""
    return f"\n\\section{{{heading}}}\n\n{body}\n"


def build():
    chunks = [PREAMBLE]
    readings = find_readings()
    missing = []

    for reading_dir, name in readings:
        guide = next(reading_dir.glob("*_Claude_Guide.tex"), None)
        notes = next(reading_dir.glob("*_Notes.tex"), None)

        subtitle = ""
        for candidate in (guide, notes):
            if candidate:
                subtitle = extract_subtitle(candidate.read_text(encoding="utf-8"))
                if subtitle:
                    break

        chunks.append(f"\n\n% {'=' * 60}\n\\part{{{escape(name)}}}\n")
        if subtitle:
            chunks.append(f"\\begin{{center}}\n{subtitle}\n\\end{{center}}\n")

        # Claude first, then mine.
        if guide:
            chunks.append(section_for(guide, reading_dir, "Claude Guide"))
        else:
            missing.append(f"{name}: no Claude guide")
        if notes:
            chunks.append(section_for(notes, reading_dir, "My Notes"))
        else:
            missing.append(f"{name}: no notes")

    chunks.append("\n\\end{document}\n")
    return "".join(chunks), readings, missing


def escape(s):
    """Escape the LaTeX specials that realistically appear in folder names."""
    return s.replace("&", r"\&").replace("_", r"\_").replace("%", r"\%")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pdf", action="store_true", help="compile with latexmk")
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the compendium is out of date; write nothing",
    )
    args = ap.parse_args()

    text, readings, missing = build()

    if args.check:
        current = OUT_TEX.read_text(encoding="utf-8") if OUT_TEX.exists() else ""
        if current != text:
            print("compendium.tex is out of date — run tools/build_compendium.py")
            return 1
        print("compendium.tex is up to date")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT_TEX.relative_to(REPO)} — {len(readings)} readings")
    for warning in missing:
        print(f"  warning: {warning}")

    if args.pdf:
        # -cd so relative image paths resolve from the repo root, not Compendium/.
        proc = subprocess.run(
            [
                "latexmk", "-pdf", "-interaction=nonstopmode",
                "-halt-on-error", "-quiet",
                f"-outdir={OUT_DIR}",
                str(OUT_TEX),
            ],
            cwd=REPO,
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout[-3000:] + proc.stderr[-2000:])
            print("\nlatexmk failed — see log above")
            return proc.returncode
        print(f"Built {(OUT_DIR / 'compendium.pdf').relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
