#!/usr/bin/env python3
"""
Compendium builder — stitches the Synthetic Overview and every reading's
notes into one navigable PDF.

Structure of the generated document:

  * front matter: title page and a hyperlinked table of contents
  * first chapter: the Synthetic Overview, pulled live from
    `Comprehensive Content/Synthetic Overview.tex` so edits there flow
    through on the next build
  * one chapter per reading, ordered chronologically by the year in the
    folder name, each starting on a fresh page
  * a running header on every page carrying author/year and short title
  * readings from `Extra Readings/` are marked EXTERNAL in blue

The generated file is disposable — it is rewritten from scratch on every
run and should never be hand-edited. Edit the source notes instead.

Usage:
    python3 tools/build_compendium.py            # write .tex only
    python3 tools/build_compendium.py --pdf      # write .tex and compile
    python3 tools/build_compendium.py --check    # exit 1 if stale (for hooks)

No dependencies beyond the standard library; `--pdf` shells out to latexmk.
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "Comprehensive Content" / "Compendium"
OUT_TEX = OUT_DIR / "compendium.tex"

# Pulled in as the opening chapter rather than scanned as a reading.
OVERVIEW = REPO / "Comprehensive Content" / "Synthetic Overview.tex"

# Anything under this folder is flagged EXTERNAL in the compendium.
EXTRA_DIR_NAME = "Extra Readings"

# Folders that hold no readings.
SKIP_DIRS = {
    "tools", "Exam Writing", "Comprehensive Content", "Compendium",
    ".git", "__pycache__",
}

BODY_RE = re.compile(r"\\begin\{document\}(.*)\\end\{document\}", re.DOTALL)
TITLE_RE = re.compile(r"\\title\{(.*?)\n?\}\s*\n\s*\\author", re.DOTALL)
GRAPHICS_RE = re.compile(r"(\\includegraphics)(\[[^\]]*\])?\{([^}]*)\}")
YEAR_RE = re.compile(r"(\d{4})")
QUOTED_RE = re.compile(r"``(.+?)''", re.DOTALL)
ITALIC_RE = re.compile(r"\\textit\{([^}]*)\}")

# Stripped from each body: the standalone-document furniture.
STRIP_LINES = re.compile(
    r"^\s*\\(maketitle|tableofcontents|newpage|clearpage|thispagestyle\{[^}]*\})\s*$",
    re.MULTILINE,
)

# Each reading is a \chapter, so a source \section already sits at the right
# depth and needs no demotion. Starred headings are unstarred instead, so they
# earn a table-of-contents entry; with secnumdepth at -1 nothing gains a number,
# so this is invisible on the page.
UNSTAR = [
    (re.compile(r"\\subsection\*"), r"\\subsection"),
    (re.compile(r"\\section\*"), r"\\section"),
]

# Longer than this and a title is trimmed for the running header only.
HEADER_TITLE_MAX = 58

PREAMBLE = r"""% ---------------------------------------------------------------
%  AUTO-GENERATED by tools/build_compendium.py — DO NOT EDIT.
%  Edit the individual reading notes and re-run the builder.
% ---------------------------------------------------------------
\documentclass[11pt,oneside,openany]{book}
\usepackage[margin=1in,headheight=15pt]{geometry}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsfonts}
\usepackage{enumitem}
\usepackage{graphicx}
\usepackage{parskip}
\usepackage{titlesec}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{hyperref}

% Figures are referenced by repo-relative path, which resolves when this file
% is compiled from the repo root (what tools/build_*.py do). An editor that
% auto-builds it from its own folder would otherwise find no images at all, so
% offer the way back up to the root as a second search path.
\graphicspath{{./}{../../}}

\hypersetup{
  colorlinks=true,
  linkcolor=[HTML]{1F4E79},
  linktoc=all,
  bookmarksnumbered=false,
  bookmarksopen=true,
  pdftitle={2026 Comprehensive Exam — Collected Notes},
  pdfauthor={Ryan Gibbons},
}

% Readings drawn from outside the official list.
\definecolor{externalblue}{HTML}{5B9BD5}
\newcommand{\extmark}{%
  \texorpdfstring{\textcolor{externalblue}{\textbf{EXTERNAL}}}{[EXTERNAL]}}

% Chapters carry the title alone — no "Chapter N" line, nothing numbered.
\setcounter{secnumdepth}{-1}
\setcounter{tocdepth}{1}

% Running header: author/year at the left, short title at the right. The
% chapter-opening page uses `plain`, so redefine that to match and every
% page ends up carrying the header.
%
% \chapter and \section would otherwise reset the marks themselves — and a
% section name like "General Notes" is the same in every reading, so it makes
% a useless header. Silence both and set the marks explicitly per chapter.
\renewcommand{\chaptermark}[1]{}
\renewcommand{\sectionmark}[1]{}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\nouppercase{\leftmark}}
\fancyhead[R]{\small\itshape\nouppercase{\rightmark}}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\fancypagestyle{plain}{%
  \fancyhf{}%
  \fancyhead[L]{\small\nouppercase{\leftmark}}%
  \fancyhead[R]{\small\itshape\nouppercase{\rightmark}}%
  \fancyfoot[C]{\thepage}%
  \renewcommand{\headrulewidth}{0.4pt}%
}

\title{\textbf{2026 Comprehensive Exam}\\[0.3em]
\large Collected Notes}
\author{Ryan Gibbons}
\date{\today}

\begin{document}

\frontmatter
\maketitle
\tableofcontents

\mainmatter
"""


def year_of(name):
    """Publication year parsed from a folder name like 'Lipset and Rokkan 1967'."""
    hits = YEAR_RE.findall(name)
    return int(hits[-1]) if hits else 9999


def find_readings():
    """Return [(dir_path, display_name, is_external)] ordered chronologically."""
    found = {}
    for tex in REPO.rglob("*_Notes.tex"):
        d = tex.parent
        rel = d.relative_to(REPO)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        found[d] = (d.name, EXTRA_DIR_NAME in rel.parts)
    # Chronological by the year in the reading's name; ties fall back to
    # alphabetical so the order is stable between runs.
    return sorted(
        ((d, name, ext) for d, (name, ext) in found.items()),
        key=lambda item: (year_of(item[1]), item[1].lower()),
    )


def extract_subtitle(src):
    """Pull the citation line out of \\title{...}, minus the bolded heading."""
    m = TITLE_RE.search(src)
    if not m:
        return ""
    title = m.group(1)
    # Drop the leading \textbf{...} (the "Dahl 1972 RG Notes" part) and
    # the \large switch, keeping the human-readable citation beneath it.
    title = re.sub(r"\\textbf\{[^}]*\}\s*\\\\", "", title, count=1)
    title = title.replace(r"\large", "")
    parts = [p.strip() for p in title.split(r"\\") if p.strip()]
    return " ".join(parts)


def short_title(citation):
    """The work's own title, for the running header.

    Most citations put it in \\textit{}. Chapters and essays quote the piece
    and italicise the volume that contains it, so a quotation that opens
    before the first italics wins.
    """
    quoted = QUOTED_RE.search(citation)
    italic = ITALIC_RE.search(citation)
    if quoted and (not italic or quoted.start() < italic.start()):
        title = quoted.group(1)
    elif italic:
        title = italic.group(1)
    else:
        return ""
    title = re.sub(r"\s+", " ", title).strip().rstrip(".").strip()
    if len(title) > HEADER_TITLE_MAX:
        title = title[:HEADER_TITLE_MAX].rsplit(" ", 1)[0] + r"\ldots"
    return title


def transform(src, source_dir):
    """Strip a standalone .tex down to an includable body."""
    m = BODY_RE.search(src)
    body = m.group(1) if m else src
    body = STRIP_LINES.sub("", body)
    for pattern, repl in UNSTAR:
        body = pattern.sub(repl, body)

    # Images are referenced bare (e.g. {fig1.jpg}) and collide across
    # folders, so rewrite each to a repo-relative path.
    rel = source_dir.relative_to(REPO).as_posix()

    def fix(match):
        cmd, opts, target = match.groups()
        if "/" in target:  # already qualified
            return match.group(0)
        return f'{cmd}{opts or ""}{{"{rel}/{target}"}}'

    body = GRAPHICS_RE.sub(fix, body)
    return body.strip()


def chapter_block(name, citation, body, external=False):
    """One chapter: heading, running marks, citation, body, page break."""
    tag = r" \extmark" if external else ""
    toc_entry = f"{escape(name)}{tag}"
    heading = f"{escape(name)}{tag}"
    header_left = f"{escape(name)}{tag}"
    header_right = short_title(citation)

    out = [
        f"\n\n% {'=' * 60}\n",
        f"\\chapter[{toc_entry}]{{{heading}}}\n",
        f"\\markboth{{{header_left}}}{{{header_right}}}\n",
    ]
    if citation:
        out.append(f"\\begin{{center}}\n{citation}\n\\end{{center}}\n\n")
    out.append(body)
    out.append("\n\n\\clearpage\n")
    return "".join(out)


def build():
    chunks = [PREAMBLE]
    missing = []

    # --- Synthetic Overview, first and pulled live -----------------------
    if OVERVIEW.exists():
        src = OVERVIEW.read_text(encoding="utf-8")
        body = transform(src, OVERVIEW.parent)
        chunks.append(
            chapter_block("Synthetic Overview", "", body, external=False)
        )
    else:
        missing.append(f"{OVERVIEW.name} not found — overview chapter skipped")

    # The overview's own themes are worth listing; the readings all share the
    # same five boilerplate section names, so below this point the contents
    # lists chapters only.
    chunks.append("\n\\addtocontents{toc}{\\setcounter{tocdepth}{0}}\n")

    # --- One chapter per reading, chronological --------------------------
    readings = find_readings()
    for reading_dir, name, external in readings:
        notes = next(reading_dir.glob("*_Notes.tex"), None)
        if not notes:
            missing.append(f"{name}: no notes")
            continue
        src = notes.read_text(encoding="utf-8")
        chunks.append(
            chapter_block(
                name,
                extract_subtitle(src),
                transform(src, reading_dir),
                external=external,
            )
        )

    chunks.append("\n\\end{document}\n")
    return "".join(chunks), readings, missing


def escape(s):
    """Escape the LaTeX specials that realistically appear in folder names."""
    return s.replace("&", r"\&").replace("_", r"\_").replace("%", r"\%")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pdf", action="store_true", help="compile with latexmk")
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the compendium is out of date; write nothing",
    )
    args = ap.parse_args()

    text, readings, missing = build()

    if args.check:
        current = OUT_TEX.read_text(encoding="utf-8") if OUT_TEX.exists() else ""
        if current != text:
            print("compendium.tex is out of date — run tools/build_compendium.py")
            return 1
        print("compendium.tex is up to date")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(text, encoding="utf-8")
    externals = sum(1 for _, _, ext in readings if ext)
    print(
        f"Wrote {OUT_TEX.relative_to(REPO)} — {len(readings)} readings "
        f"({externals} external), chronological"
    )
    for warning in missing:
        print(f"  warning: {warning}")

    if args.pdf:
        # Build into a private scratch dir rather than beside the .tex. The
        # editor's LaTeX extension auto-builds compendium.tex whenever this
        # script rewrites it, and two latexmk runs sharing an output directory
        # trample each other's .aux/.toc — which silently yields a PDF with an
        # empty table of contents. Only the finished PDF is copied back out.
        aux = OUT_DIR / ".build"
        aux.mkdir(parents=True, exist_ok=True)
        # cwd=REPO so the repo-relative image paths inside resolve.
        proc = subprocess.run(
            [
                "latexmk", "-pdf", "-interaction=nonstopmode",
                "-halt-on-error", "-quiet",
                f"-outdir={aux.relative_to(REPO)}",
                str(OUT_TEX.relative_to(REPO)),
            ],
            cwd=REPO,
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout[-3000:] + proc.stderr[-2000:])
            print("\nlatexmk failed — see log above")
            return proc.returncode

        built = aux / "compendium.pdf"
        if not built.exists():
            print("latexmk reported success but produced no PDF")
            return 1
        shutil.copy2(built, OUT_DIR / "compendium.pdf")

        # A table of contents that came out empty means the run raced with
        # another build; say so rather than shipping a broken PDF silently.
        toc = aux / "compendium.toc"
        entries = toc.read_text(encoding="utf-8").count("contentsline") if toc.exists() else 0
        if entries == 0:
            print("warning: table of contents is empty — was another "
                  "LaTeX build running at the same time?")
        print(
            f"Built {(OUT_DIR / 'compendium.pdf').relative_to(REPO)} "
            f"({entries} contents entries)"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
